#
# this workflow will move the release flagged as 'pre-release' to the release named 'latest'
#
# see ./scripts/release.sh for details
#
name: 'release'

on:
  # this workflow needs to be triggered manually
  workflow_dispatch:

jobs:
  update-latest:
    runs-on: ubuntu-latest
    # ensure only one pipeline is running this workflow at a time
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      # only run on main branch
      - name: Check branch
        if: github.event.branch != 'main'
        run: |
          echo "::error::Workflow can only be run on main branch"
          exit 1

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: release
        run: |
          export GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          export GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK="${{ secrets.GCHAT_RELEASE_ANNOUNCEMENTS_WEBHOOK }}"

          pnpm release

